version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env